### ISSUE TITLE
Problem when Run it

### ISSUE THREAD

**Issue by hacker9631** [Arab-developers/HackerMode#3]
When I run the tool this message appears: 
Refresh the time from within the 'Hacker Mode' application.

Please help me

**Comment by wadfur** [comment]
when i run HackerMode this message appears --

┌──(alrsheed㉿kali)-[~]
└─$ sudo HackerMode
python3: can't open file '/root/.HackerMode/HackerMode': [Errno 2] No such file or directory

**Comment by MasterXCode** [comment]
> When I run the tool this message appears:
> Refresh the time from within the 'Hacker Mode' application.
> 
> Please help me

He has a youtube channel called Vairous 7x   . he has provided the link to the application it the tool's video

**Comment by Qqrryd** [comment]
> عند تشغيل الأداة ، تظهر هذه الرسالة: قم
> بتحديث الوقت من داخل تطبيق "وضع القرصنة".
> 
> من فضلك ساعدنى
رابط التطبيق 
https://www.mediafire.com/file/r1u3pc3g9e2y1z8/Hacker_Mode_Release.apk/file
